services:
  cymo.entity_rating_bundle.manager:
      class: Cymo\Bundle\EntityRatingBundle\Manager\EntityRatingManager
      arguments:
      - '@annotations.reader'
      - '@cymo.entity_rating_bundle.form_factory'
      - '@service_container'
  cymo.entity_rating_bundle.form_factory:
      class: Cymo\Bundle\EntityRatingBundle\Factory\EntityRatingFormFactory
      arguments:
      - '@form.factory'